### ISSUE TITLE
vgpu 的疑惑

### ISSUE THREAD

**Issue by phoenixzjh** [justin-himself/NVIDIA-VGPU-Driver-Archive#1]
最近在研究vgpu , 本人有一台 x79 平台的服务器，显卡为 3060m 的显卡。
安装 pve 管理虚拟机，创建windows 系统，直通显卡，各种叹号，没搞定。

后来看到 nvidia 有 vgpu 虚拟gpu 技术，研究各种教程，做了各种实验，比如设置环境，安装驱动 ， unlock 等等，最近又出来一个nvidia授权服务器，完全懵逼了。

谁有比较全面一点的说明教程，或者 3060m 显卡的 虚拟化方案， 或者其它的 esxi 、hyper-v 等等的 gpu 虚拟化方案。

**Comment by codgician** [comment]
1. GRID 只支持专业卡，不支持普通的 GeForce 显卡
2. vgpu-unlock 的原理是通过魔改 host 驱动将 GeForce 显卡仿冒为专业卡以获得 vGPU 功能。该项目目前并没有支持 30 系显卡，详见：https://github.com/DualCoder/vgpu_unlock/issues/8

现阶段对于 30 系显卡还是考虑 Hyper-V 的 GPU Partitioning 吧

**Comment by phoenixzjh** [comment]
> 1. GRID 只支持专业卡，不支持普通的 GeForce 显卡
> 2. vgpu-unlock 的原理是通过魔改 host 驱动将 GeForce 显卡仿冒为专业卡以获得 vGPU 功能。该项目目前并没有支持 30 系显卡，详见：[Ampere support DualCoder/vgpu_unlock#8](https://github.com/DualCoder/vgpu_unlock/issues/8)
> 
> 现阶段对于 30 系显卡还是考虑 Hyper-V 的 GPU Partitioning 吧

多谢
