### ISSUE TITLE
PVE14 VPGU问题

### ISSUE THREAD

**Issue by lategege** [justin-himself/NVIDIA-VGPU-Driver-Archive#2]
X99平台，PVE 14，内核版本5.15.102 ，显卡是Tesla P40，驱动安装的是NVIDIA-GRID-Linux-KVM-525.60.12-525.60.13-527.41.zip这个版本，碰到的问题是启动卡死，但是直通后安装普通驱动能够正常使用。不知道问题出在了哪？是内核版本和驱动版本对不上吗？网上也查不到对应的驱动内核对应的表。

**Comment by justin-himself** [comment]
启动卡死具体是什么症状？是宿主机还是虚拟机卡死？能不能提供卡死时的屏显看一下

**Comment by glynnt** [comment]
Debian遇到类似问题，启动时nvidia-vgpud, nvidia-vgpu-mgr无法正常启动，用UEFI重装系统后问题解决。
