### ISSUE TITLE
驱动win11无法安装

### ISSUE THREAD

**Issue by vission8899** [justin-himself/NVIDIA-VGPU-Driver-Archive#5]
![image](https://github.com/justin-himself/NVIDIA-VGPU-Driver-Archive/assets/43826126/beb303fb-ee68-411b-87e7-ed291d47f9c7)

**Comment by justin-himself** [comment]
请提供更多信息。

1. Proxmox Passthrough 的设置
2. Windows Device Manager 包含 Passthrough 显卡的截图
3. 你尝试安装驱动文件的全名
4. 尝试 `setup.exe -log:"C:\NVlog" -loglevel:6` 并附上日志 （我没有尝试过这样打日志，如果有用请附上日志）

**Comment by justin-himself** [comment]
Not enough details.
Note: 这个repo原则上只提供驱动，不负责解决你使用驱动过程中碰到的问题；如果你真的碰到解决不了的问题请提供详细的信息，就给一张错误截图截图然后期待我帮你解决问题是不现实的。
